#import <Foundation/Foundation.h>
#import "SWGListAvailableNumbersFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGAvailablenumbersApi: NSObject <SWGApi>

extern NSString* kSWGAvailablenumbersApiErrorDomain;
extern NSInteger kSWGAvailablenumbersApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// 
/// 
///
/// @param filtersPhoneNumber Phone number filter (optional)
/// @param filtersCountryCode Country Code filter (optional)
/// @param filtersNpa Area Code filter (North America only) (optional)
/// @param filtersNxx 2nd set of 3 digits filter (North America only) (optional)
/// @param filtersXxxx NANP XXXX filter (optional)
/// @param filtersCity City filter (optional)
/// @param filtersProvince State or Province (postal code) filter (optional)
/// @param filtersCountry Country (postal code) filter (optional)
/// @param filtersPrice Price filter (optional)
/// @param filtersCategory Category filter (optional)
/// @param filtersIsTollFree Toll-free status filter (optional)
/// @param sortInternal Internal (quasi-random) sorting (optional)
/// @param sortPrice Price sorting (optional)
/// @param sortPhoneNumber Phone number sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:429 message:"Forbidden"
///
/// @return SWGListAvailableNumbersFull*
-(NSNumber*) listAvailablePhoneNumbersWithFiltersPhoneNumber: (NSArray<NSString*>*) filtersPhoneNumber
    filtersCountryCode: (NSArray<NSString*>*) filtersCountryCode
    filtersNpa: (NSArray<NSString*>*) filtersNpa
    filtersNxx: (NSArray<NSString*>*) filtersNxx
    filtersXxxx: (NSArray<NSString*>*) filtersXxxx
    filtersCity: (NSArray<NSString*>*) filtersCity
    filtersProvince: (NSArray<NSString*>*) filtersProvince
    filtersCountry: (NSArray<NSString*>*) filtersCountry
    filtersPrice: (NSArray<NSString*>*) filtersPrice
    filtersCategory: (NSArray<NSString*>*) filtersCategory
    filtersIsTollFree: (NSArray<NSString*>*) filtersIsTollFree
    sortInternal: (NSString*) sortInternal
    sortPrice: (NSString*) sortPrice
    sortPhoneNumber: (NSString*) sortPhoneNumber
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListAvailableNumbersFull* output, NSError* error)) handler;



@end
