#import <Foundation/Foundation.h>
#import "SWGAccountFull.h"
#import "SWGListAccountsFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGAccountsApi: NSObject <SWGApi>

extern NSString* kSWGAccountsApiErrorDomain;
extern NSInteger kSWGAccountsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Retrieve details of an individual account
/// This service shows the details of an individual account. See Accounts for more info on the properties.
///
/// @param accountId Account ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGAccountFull*
-(NSNumber*) getAccountWithAccountId: (NSNumber*) accountId
    completionHandler: (void (^)(SWGAccountFull* output, NSError* error)) handler;


/// Get a list of accounts visible to the authenticated user or client
/// This service lists the accounts accessible to the authenticated client. In most cases, there will only be one such account. See Accounts for more info on the properties.
///
/// @param filtersId ID filter (optional)
/// @param sortId ID sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access"
///
/// @return SWGListAccountsFull*
-(NSNumber*) listAccountsWithFiltersId: (NSArray<NSString*>*) filtersId
    sortId: (NSString*) sortId
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListAccountsFull* output, NSError* error)) handler;



@end
