#import <Foundation/Foundation.h>
#import "SWGListCallerIdsFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGCalleridsApi: NSObject <SWGApi>

extern NSString* kSWGCalleridsApiErrorDomain;
extern NSInteger kSWGCalleridsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Show the Caller ID options a given extension can use
/// Get Caller ID
///
/// @param accountId Account ID
/// @param extensionId Extension ID
/// @param filtersNumber Number filter (optional)
/// @param filtersName Name filter (optional)
/// @param sortNumber Number sorting (optional)
/// @param sortName Name sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListCallerIdsFull*
-(NSNumber*) getCallerIdsWithAccountId: (NSNumber*) accountId
    extensionId: (NSNumber*) extensionId
    filtersNumber: (NSArray<NSString*>*) filtersNumber
    filtersName: (NSArray<NSString*>*) filtersName
    sortNumber: (NSString*) sortNumber
    sortName: (NSString*) sortName
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListCallerIdsFull* output, NSError* error)) handler;



@end
