#import <Foundation/Foundation.h>
#import "SWGPhoneNumberFull.h"
#import "SWGCreatePhoneNumberParams.h"
#import "SWGListPhoneNumbersFull.h"
#import "SWGReplacePhoneNumberParams.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGPhonenumbersApi: NSObject <SWGApi>

extern NSString* kSWGPhonenumbersApiErrorDomain;
extern NSInteger kSWGPhonenumbersApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Add a phone number to an account
/// See Intro to Account Phone Numbers for more info on the properties to use.
///
/// @param accountId Account ID
/// @param data Phone Number data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGPhoneNumberFull*
-(NSNumber*) createAccountPhoneNumberWithAccountId: (NSNumber*) accountId
    data: (SWGCreatePhoneNumberParams*) data
    completionHandler: (void (^)(SWGPhoneNumberFull* output, NSError* error)) handler;


/// Show details of an individual phone number
/// See Intro to Account Phone Numbers for more info on the properties.
///
/// @param accountId Account ID
/// @param numberId Number ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGPhoneNumberFull*
-(NSNumber*) getAccountPhoneNumberWithAccountId: (NSNumber*) accountId
    numberId: (NSNumber*) numberId
    completionHandler: (void (^)(SWGPhoneNumberFull* output, NSError* error)) handler;


/// Get a list of phone numbers registered to an account
/// See Intro to Account Phone Numbers for more info on the properties.
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersName Name filter (optional)
/// @param filtersPhoneNumber Phone number filter (optional)
/// @param sortId ID sorting (optional)
/// @param sortName Name sorting (optional)
/// @param sortPhoneNumber Phone number sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListPhoneNumbersFull*
-(NSNumber*) listAccountPhoneNumbersWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersName: (NSArray<NSString*>*) filtersName
    filtersPhoneNumber: (NSArray<NSString*>*) filtersPhoneNumber
    sortId: (NSString*) sortId
    sortName: (NSString*) sortName
    sortPhoneNumber: (NSString*) sortPhoneNumber
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListPhoneNumbersFull* output, NSError* error)) handler;


/// Update the settings for an existing phone number on your account
/// See Intro to Account Phone Numbers for more info on the properties.
///
/// @param accountId Account ID
/// @param numberId Number ID
/// @param data Phone Number data (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGPhoneNumberFull*
-(NSNumber*) replaceAccountPhoneNumberWithAccountId: (NSNumber*) accountId
    numberId: (NSNumber*) numberId
    data: (SWGReplacePhoneNumberParams*) data
    completionHandler: (void (^)(SWGPhoneNumberFull* output, NSError* error)) handler;



@end
