/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RuleSetAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleSetActionTests
    {
        // TODO uncomment below to declare an instance variable for RuleSetAction
        //private RuleSetAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleSetAction
            //instance = new RuleSetAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleSetAction
        /// </summary>
        [Test]
        public void RuleSetActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuleSetAction
            //Assert.IsInstanceOfType<RuleSetAction> (instance, "variable 'instance' is a RuleSetAction");
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'HoldMusic'
        /// </summary>
        [Test]
        public void HoldMusicTest()
        {
            // TODO unit test for the property 'HoldMusic'
        }
        /// <summary>
        /// Test the property 'Greeting'
        /// </summary>
        [Test]
        public void GreetingTest()
        {
            // TODO unit test for the property 'Greeting'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Menu'
        /// </summary>
        [Test]
        public void MenuTest()
        {
            // TODO unit test for the property 'Menu'
        }
        /// <summary>
        /// Test the property 'Queue'
        /// </summary>
        [Test]
        public void QueueTest()
        {
            // TODO unit test for the property 'Queue'
        }
        /// <summary>
        /// Test the property 'Trunk'
        /// </summary>
        [Test]
        public void TrunkTest()
        {
            // TODO unit test for the property 'Trunk'
        }

    }

}
