/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The Full Account Object includes all of the properties in the Account Summary Object, along with the following:
type AccountFull struct {

	// Account ID. Sometimes referred to as \"Voip ID\" or \"voip_id\".
	Id int32 `json:"id,omitempty"`

	// Name on the account. Read-only.
	Name string `json:"name,omitempty"`

	// Account user name
	Username string `json:"username,omitempty"`

	// Account password. For security reason, this is masked as \"**\"
	Password string `json:"password,omitempty"`

	// If this account is a subaccount, this property shows the master account that it belongs to. Otherwise it is NULL. Read-only. Output is an Account Summary Object.
	MasterAccount AccountSummary `json:"master_account,omitempty"`

	// Contact Object. See below for details.
	Contact ContactAccount `json:"contact,omitempty"`

	// Contact Object for billing purposes. See below for details.
	BillingContact ContactAccount `json:"billing_contact,omitempty"`
}
