/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type ContactSubaccount struct {

	// Contact name
	Name string `json:"name,omitempty"`

	Address Address `json:"address,omitempty"`

	// Primary email address. Required.
	PrimaryEmail string `json:"primary_email,omitempty"`

	// Alternate email address
	AlternateEmail string `json:"alternate_email,omitempty"`

	// Company name
	Company string `json:"company,omitempty"`

	// Phone number. Required.
	Phone string `json:"phone,omitempty"`

	// Fax number
	Fax string `json:"fax,omitempty"`
}
