/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type CreateExtensionParams struct {

	// Caller ID
	CallerId string `json:"caller_id,omitempty"`

	// Extension type
	UsageType string `json:"usage_type,omitempty"`

	// Allows call waiting
	AllowsCallWaiting bool `json:"allows_call_waiting,omitempty"`

	// Extension number (auto-generated if empty)
	Extension int32 `json:"extension,omitempty"`

	// Include in dial-by-name directory
	IncludeInDirectory bool `json:"include_in_directory,omitempty"`

	// Name (auto-generated if empty)
	Name string `json:"name,omitempty"`

	// Contact name
	FullName string `json:"full_name,omitempty"`

	// Timezone
	Timezone string `json:"timezone,omitempty"`

	// Recording lookup object
	NameGreeting Object `json:"name_greeting,omitempty"`

	// Recording lookup object
	VoicemailGreetingAlternate Object `json:"voicemail[greeting][alternate],omitempty"`

	// Local area code
	LocalAreaCode int32 `json:"local_area_code,omitempty"`

	// Enable the \"leave a message\" prompt for voicemail
	VoicemailGreetingEnableLeaveMessagePrompt bool `json:"voicemail[greeting][enable_leave_message_prompt],omitempty"`

	// Voicemail enabled
	VoicemailEnabled bool `json:"voicemail[enabled],omitempty"`

	// Enable outgoing calls
	EnableOutboundCalls bool `json:"enable_outbound_calls,omitempty"`

	// Enable Call Waiting
	EnableCallWaiting bool `json:"enable_call_waiting,omitempty"`

	// Voicemail password
	VoicemailPassword int32 `json:"voicemail[password],omitempty"`

	// Voicemail greeting type
	VoicemailGreetingType string `json:"voicemail[greeting][type],omitempty"`

	// Recording lookup object
	VoicemailGreetingStandard Object `json:"voicemail[greeting][standard],omitempty"`

	// Voicemail transcription type
	VoicemailTranscription string `json:"voicemail[transcription],omitempty"`

	// Email notifications for voicemails. Can be a single email or an array of emails
	VoicemailNotificationsEmails []string `json:"voicemail[notifications][emails],omitempty"`

	// SMS notifications for voicemails
	VoicemailNotificationsSms string `json:"voicemail[notifications][sms],omitempty"`

	// Email notifications for calls. Can be a single email or an array of emails
	CallNotificationsEmails []string `json:"call_notifications[emails],omitempty"`

	// SMS notifications for calls
	CallNotificationsSms string `json:"call_notifications[sms],omitempty"`
}
