/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The Full Extension Object has the same properties as the Extension Summary Object, along with the following:
type ExtensionSummary struct {

	// ID of the extension. This is the internal Phone.com ID, not the extension number callers may dial.
	Id int32 `json:"id,omitempty"`

	// User-supplied name for the extension. On POST, leaving this empty will result in an auto-generated value. On PUT, this field is required.
	Name string `json:"name,omitempty"`

	// Extension number that callers may dial. On POST, leaving this empty will result in an auto-generated value. On PUT, this field is required.
	Extension int32 `json:"extension,omitempty"`
}
