/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type ReplacePhoneNumberParams struct {

	// Route lookup object
	Route Object `json:"route,omitempty"`

	// Phone Name
	Name string `json:"name,omitempty"`

	// Block incoming calls
	BlockIncoming bool `json:"block_incoming,omitempty"`

	// Block anonymous calls
	BlockAnonymous bool `json:"block_anonymous,omitempty"`

	// Caller ID name
	CallerIdName string `json:"caller_id[name],omitempty"`

	// Caller ID type
	CallerIdType string `json:"caller_id[type],omitempty"`

	// 'application' or 'extension'
	SmsForwardingType string `json:"sms_forwarding[type],omitempty"`

	// Application lookup object
	SmsForwardingApplication Object `json:"sms_forwarding[application],omitempty"`

	// Extension lookup object
	SmsForwardingExtension Object `json:"sms_forwarding[extension],omitempty"`

	// Pool lookup object
	PoolItem Object `json:"pool_item,omitempty"`

	// Call notifications for emails. Can be a single email or an array of emails
	CallNotificationsEmails []string `json:"call_notifications[emails],omitempty"`

	// Call notification for SMS
	CallNotificationsSms string `json:"call_notifications[sms],omitempty"`
}
