/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The SMS Summary Object is used to briefly represent a sms. It can be seen in several places throughout this API. Here are the properties:
type SmsSummary struct {

	// Unique SMS ID. Read-only.
	Id string `json:"id,omitempty"`

	// Caller ID number to display on the incoming/outgoing SMS message. For an outgoing message, it must be a phone number associated with your Phone.com account.
	From string `json:"from,omitempty"`

	// An array of SMS recipients.
	To []Recipient `json:"to,omitempty"`

	// Direction of SMS. 'in' for Incoming messages, 'out' for Outgoing messages.
	Direction string `json:"direction,omitempty"`
}
