/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

import (
	"time"
)

// The Full SMS Object includes all of the properties in the SMS Summary Object, along with several more.
type SmsFull struct {

	// Unique SMS ID. Read-only.
	Id string `json:"id,omitempty"`

	// Caller ID number to display on the incoming/outgoing SMS message. For an outgoing message, it must be a phone number associated with your Phone.com account.
	From string `json:"from,omitempty"`

	// An array of SMS recipients.
	To []Recipient `json:"to,omitempty"`

	// Direction of SMS. 'in' for Incoming messages, 'out' for Outgoing messages.
	Direction string `json:"direction,omitempty"`

	// Unix time stamp representing the UTC time that the object was created in the Phone.com API system.
	CreatedEpoch int32 `json:"created_epoch,omitempty"`

	// Date string representing the UTC time that the object was created in the Phone.com API system.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Body of the SMS text
	Text string `json:"text,omitempty"`
}
