/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MenusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MenusApiTests
    {
        private MenusApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MenusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MenusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MenusApi
            //Assert.IsInstanceOfType(typeof(MenusApi), instance, "instance is a MenusApi");
        }

        
        /// <summary>
        /// Test CreateAccountMenu
        /// </summary>
        [Test]
        public void CreateAccountMenuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //CreateMenuParams data = null;
            //var response = instance.CreateAccountMenu(accountId, data);
            //Assert.IsInstanceOf<MenuFull> (response, "response is MenuFull");
        }
        
        /// <summary>
        /// Test DeleteAccountMenu
        /// </summary>
        [Test]
        public void DeleteAccountMenuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? menuId = null;
            //var response = instance.DeleteAccountMenu(accountId, menuId);
            //Assert.IsInstanceOf<DeleteMenu> (response, "response is DeleteMenu");
        }
        
        /// <summary>
        /// Test GetAccountMenu
        /// </summary>
        [Test]
        public void GetAccountMenuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? menuId = null;
            //var response = instance.GetAccountMenu(accountId, menuId);
            //Assert.IsInstanceOf<MenuFull> (response, "response is MenuFull");
        }
        
        /// <summary>
        /// Test ListAccountMenus
        /// </summary>
        [Test]
        public void ListAccountMenusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //List<string> filtersId = null;
            //List<string> filtersName = null;
            //string sortId = null;
            //string sortName = null;
            //int? limit = null;
            //int? offset = null;
            //string fields = null;
            //var response = instance.ListAccountMenus(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);
            //Assert.IsInstanceOf<ListMenusFull> (response, "response is ListMenusFull");
        }
        
        /// <summary>
        /// Test ReplaceAccountMenu
        /// </summary>
        [Test]
        public void ReplaceAccountMenuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? menuId = null;
            //ReplaceMenuParams data = null;
            //var response = instance.ReplaceAccountMenu(accountId, menuId, data);
            //Assert.IsInstanceOf<MenuFull> (response, "response is MenuFull");
        }
        
    }

}
