/* 
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QueuesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class QueuesApiTests
    {
        private QueuesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new QueuesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QueuesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' QueuesApi
            //Assert.IsInstanceOfType(typeof(QueuesApi), instance, "instance is a QueuesApi");
        }

        
        /// <summary>
        /// Test CreateAccountQueue
        /// </summary>
        [Test]
        public void CreateAccountQueueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //CreateQueueParams data = null;
            //var response = instance.CreateAccountQueue(accountId, data);
            //Assert.IsInstanceOf<QueueFull> (response, "response is QueueFull");
        }
        
        /// <summary>
        /// Test DeleteAccountQueue
        /// </summary>
        [Test]
        public void DeleteAccountQueueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? queueId = null;
            //var response = instance.DeleteAccountQueue(accountId, queueId);
            //Assert.IsInstanceOf<DeleteQueue> (response, "response is DeleteQueue");
        }
        
        /// <summary>
        /// Test GetAccountQueue
        /// </summary>
        [Test]
        public void GetAccountQueueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? queueId = null;
            //var response = instance.GetAccountQueue(accountId, queueId);
            //Assert.IsInstanceOf<QueueFull> (response, "response is QueueFull");
        }
        
        /// <summary>
        /// Test ListAccountQueues
        /// </summary>
        [Test]
        public void ListAccountQueuesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //List<string> filtersId = null;
            //List<string> filtersName = null;
            //string sortId = null;
            //string sortName = null;
            //int? limit = null;
            //int? offset = null;
            //string fields = null;
            //var response = instance.ListAccountQueues(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);
            //Assert.IsInstanceOf<ListQueuesFull> (response, "response is ListQueuesFull");
        }
        
        /// <summary>
        /// Test ReplaceAccountQueue
        /// </summary>
        [Test]
        public void ReplaceAccountQueueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? accountId = null;
            //int? queueId = null;
            //CreateQueueParams data = null;
            //var response = instance.ReplaceAccountQueue(accountId, queueId, data);
            //Assert.IsInstanceOf<QueueFull> (response, "response is QueueFull");
        }
        
    }

}
