#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGAvailableNumberFull
@end

@interface SWGAvailableNumberFull : SWGObject

/* Phone number, in E.164 format [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/* Human-readable formatted version of the phone number [optional]
 */
@property(nonatomic) NSString* formatted;
/* The one-time initial price for this number, in USD. Some numbers show REQUEST_QUOTE here. Please contact our sales department if you are interested in these numbers. [optional]
 */
@property(nonatomic) NSNumber* price;
/* Whether the number is toll-free [optional]
 */
@property(nonatomic) NSNumber* isTollFree;
/* The international dialing prefix for this number. For US and Canadian numbers, for example, this will be \"1\". [optional]
 */
@property(nonatomic) NSString* countryCode;
/* Area code (a.k.a. NPA). Included for North American numbers only. [optional]
 */
@property(nonatomic) NSString* npa;
/* Second 3 digits (a.k.a. NXX). Included for North American numbers only. [optional]
 */
@property(nonatomic) NSString* nxx;
/* Last 4 digits (a.k.a. XXXX). Included for North American numbers only. [optional]
 */
@property(nonatomic) NSString* xxxx;
/* City with which this number is associated, if known. Otherwise NULL. [optional]
 */
@property(nonatomic) NSString* city;
/* State or Province with which this number is associated, if known. Postal Code. Otherwise NULL. [optional]
 */
@property(nonatomic) NSString* province;
/* Country with which this number is associated, if known. Otherwise NULL. [optional]
 */
@property(nonatomic) NSString* country;

@end
