/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CreateContactParams  {
  
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("middle_name")
  private String middleName = null;
  @SerializedName("last_name")
  private String lastName = null;
  @SerializedName("prefix")
  private String prefix = null;
  @SerializedName("phonetic_first_name")
  private String phoneticFirstName = null;
  @SerializedName("phonetic_middle_name")
  private String phoneticMiddleName = null;
  @SerializedName("phonetic_last_name")
  private String phoneticLastName = null;
  @SerializedName("suffix")
  private String suffix = null;
  @SerializedName("nickname")
  private String nickname = null;
  @SerializedName("company")
  private String company = null;
  @SerializedName("department")
  private String department = null;
  @SerializedName("job_title")
  private String jobTitle = null;
  @SerializedName("emails")
  private List<Object> emails = null;
  @SerializedName("phone_numbers")
  private List<Object> phoneNumbers = null;
  @SerializedName("addresses")
  private List<Object> addresses = null;
  @SerializedName("group")
  private Object group = null;

  /**
   * First Name
   **/
  @ApiModelProperty(value = "First Name")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   * Middle Name
   **/
  @ApiModelProperty(value = "Middle Name")
  public String getMiddleName() {
    return middleName;
  }
  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  /**
   * Last Name
   **/
  @ApiModelProperty(value = "Last Name")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   * Prefix
   **/
  @ApiModelProperty(value = "Prefix")
  public String getPrefix() {
    return prefix;
  }
  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  /**
   * Phonetic First Name
   **/
  @ApiModelProperty(value = "Phonetic First Name")
  public String getPhoneticFirstName() {
    return phoneticFirstName;
  }
  public void setPhoneticFirstName(String phoneticFirstName) {
    this.phoneticFirstName = phoneticFirstName;
  }

  /**
   * Phonetic Middle Name
   **/
  @ApiModelProperty(value = "Phonetic Middle Name")
  public String getPhoneticMiddleName() {
    return phoneticMiddleName;
  }
  public void setPhoneticMiddleName(String phoneticMiddleName) {
    this.phoneticMiddleName = phoneticMiddleName;
  }

  /**
   * Phonetic Last Name
   **/
  @ApiModelProperty(value = "Phonetic Last Name")
  public String getPhoneticLastName() {
    return phoneticLastName;
  }
  public void setPhoneticLastName(String phoneticLastName) {
    this.phoneticLastName = phoneticLastName;
  }

  /**
   * Suffix
   **/
  @ApiModelProperty(value = "Suffix")
  public String getSuffix() {
    return suffix;
  }
  public void setSuffix(String suffix) {
    this.suffix = suffix;
  }

  /**
   * Nickname
   **/
  @ApiModelProperty(value = "Nickname")
  public String getNickname() {
    return nickname;
  }
  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  /**
   * Company Name
   **/
  @ApiModelProperty(value = "Company Name")
  public String getCompany() {
    return company;
  }
  public void setCompany(String company) {
    this.company = company;
  }

  /**
   * Department Name
   **/
  @ApiModelProperty(value = "Department Name")
  public String getDepartment() {
    return department;
  }
  public void setDepartment(String department) {
    this.department = department;
  }

  /**
   * Job Title
   **/
  @ApiModelProperty(value = "Job Title")
  public String getJobTitle() {
    return jobTitle;
  }
  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }

  /**
   * Email Addresses
   **/
  @ApiModelProperty(value = "Email Addresses")
  public List<Object> getEmails() {
    return emails;
  }
  public void setEmails(List<Object> emails) {
    this.emails = emails;
  }

  /**
   * Phone Numbers
   **/
  @ApiModelProperty(value = "Phone Numbers")
  public List<Object> getPhoneNumbers() {
    return phoneNumbers;
  }
  public void setPhoneNumbers(List<Object> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  /**
   * Addresses
   **/
  @ApiModelProperty(value = "Addresses")
  public List<Object> getAddresses() {
    return addresses;
  }
  public void setAddresses(List<Object> addresses) {
    this.addresses = addresses;
  }

  /**
   * Contact Group
   **/
  @ApiModelProperty(value = "Contact Group")
  public Object getGroup() {
    return group;
  }
  public void setGroup(Object group) {
    this.group = group;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateContactParams createContactParams = (CreateContactParams) o;
    return (firstName == null ? createContactParams.firstName == null : firstName.equals(createContactParams.firstName)) &&
        (middleName == null ? createContactParams.middleName == null : middleName.equals(createContactParams.middleName)) &&
        (lastName == null ? createContactParams.lastName == null : lastName.equals(createContactParams.lastName)) &&
        (prefix == null ? createContactParams.prefix == null : prefix.equals(createContactParams.prefix)) &&
        (phoneticFirstName == null ? createContactParams.phoneticFirstName == null : phoneticFirstName.equals(createContactParams.phoneticFirstName)) &&
        (phoneticMiddleName == null ? createContactParams.phoneticMiddleName == null : phoneticMiddleName.equals(createContactParams.phoneticMiddleName)) &&
        (phoneticLastName == null ? createContactParams.phoneticLastName == null : phoneticLastName.equals(createContactParams.phoneticLastName)) &&
        (suffix == null ? createContactParams.suffix == null : suffix.equals(createContactParams.suffix)) &&
        (nickname == null ? createContactParams.nickname == null : nickname.equals(createContactParams.nickname)) &&
        (company == null ? createContactParams.company == null : company.equals(createContactParams.company)) &&
        (department == null ? createContactParams.department == null : department.equals(createContactParams.department)) &&
        (jobTitle == null ? createContactParams.jobTitle == null : jobTitle.equals(createContactParams.jobTitle)) &&
        (emails == null ? createContactParams.emails == null : emails.equals(createContactParams.emails)) &&
        (phoneNumbers == null ? createContactParams.phoneNumbers == null : phoneNumbers.equals(createContactParams.phoneNumbers)) &&
        (addresses == null ? createContactParams.addresses == null : addresses.equals(createContactParams.addresses)) &&
        (group == null ? createContactParams.group == null : group.equals(createContactParams.group));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (firstName == null ? 0: firstName.hashCode());
    result = 31 * result + (middleName == null ? 0: middleName.hashCode());
    result = 31 * result + (lastName == null ? 0: lastName.hashCode());
    result = 31 * result + (prefix == null ? 0: prefix.hashCode());
    result = 31 * result + (phoneticFirstName == null ? 0: phoneticFirstName.hashCode());
    result = 31 * result + (phoneticMiddleName == null ? 0: phoneticMiddleName.hashCode());
    result = 31 * result + (phoneticLastName == null ? 0: phoneticLastName.hashCode());
    result = 31 * result + (suffix == null ? 0: suffix.hashCode());
    result = 31 * result + (nickname == null ? 0: nickname.hashCode());
    result = 31 * result + (company == null ? 0: company.hashCode());
    result = 31 * result + (department == null ? 0: department.hashCode());
    result = 31 * result + (jobTitle == null ? 0: jobTitle.hashCode());
    result = 31 * result + (emails == null ? 0: emails.hashCode());
    result = 31 * result + (phoneNumbers == null ? 0: phoneNumbers.hashCode());
    result = 31 * result + (addresses == null ? 0: addresses.hashCode());
    result = 31 * result + (group == null ? 0: group.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateContactParams {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  middleName: ").append(middleName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  prefix: ").append(prefix).append("\n");
    sb.append("  phoneticFirstName: ").append(phoneticFirstName).append("\n");
    sb.append("  phoneticMiddleName: ").append(phoneticMiddleName).append("\n");
    sb.append("  phoneticLastName: ").append(phoneticLastName).append("\n");
    sb.append("  suffix: ").append(suffix).append("\n");
    sb.append("  nickname: ").append(nickname).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  department: ").append(department).append("\n");
    sb.append("  jobTitle: ").append(jobTitle).append("\n");
    sb.append("  emails: ").append(emails).append("\n");
    sb.append("  phoneNumbers: ").append(phoneNumbers).append("\n");
    sb.append("  addresses: ").append(addresses).append("\n");
    sb.append("  group: ").append(group).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
