/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ReplaceMenuParams  {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("greeting")
  private Object greeting = null;
  @SerializedName("invalid_keypress")
  private Object invalidKeypress = null;
  @SerializedName("allow_extension_dial")
  private Boolean allowExtensionDial = null;
  @SerializedName("keypress_wait_time")
  private Integer keypressWaitTime = null;
  @SerializedName("timeout_handler")
  private Object timeoutHandler = null;
  @SerializedName("options")
  private List<Object> options = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getGreeting() {
    return greeting;
  }
  public void setGreeting(Object greeting) {
    this.greeting = greeting;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getInvalidKeypress() {
    return invalidKeypress;
  }
  public void setInvalidKeypress(Object invalidKeypress) {
    this.invalidKeypress = invalidKeypress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAllowExtensionDial() {
    return allowExtensionDial;
  }
  public void setAllowExtensionDial(Boolean allowExtensionDial) {
    this.allowExtensionDial = allowExtensionDial;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getKeypressWaitTime() {
    return keypressWaitTime;
  }
  public void setKeypressWaitTime(Integer keypressWaitTime) {
    this.keypressWaitTime = keypressWaitTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getTimeoutHandler() {
    return timeoutHandler;
  }
  public void setTimeoutHandler(Object timeoutHandler) {
    this.timeoutHandler = timeoutHandler;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getOptions() {
    return options;
  }
  public void setOptions(List<Object> options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplaceMenuParams replaceMenuParams = (ReplaceMenuParams) o;
    return (name == null ? replaceMenuParams.name == null : name.equals(replaceMenuParams.name)) &&
        (greeting == null ? replaceMenuParams.greeting == null : greeting.equals(replaceMenuParams.greeting)) &&
        (invalidKeypress == null ? replaceMenuParams.invalidKeypress == null : invalidKeypress.equals(replaceMenuParams.invalidKeypress)) &&
        (allowExtensionDial == null ? replaceMenuParams.allowExtensionDial == null : allowExtensionDial.equals(replaceMenuParams.allowExtensionDial)) &&
        (keypressWaitTime == null ? replaceMenuParams.keypressWaitTime == null : keypressWaitTime.equals(replaceMenuParams.keypressWaitTime)) &&
        (timeoutHandler == null ? replaceMenuParams.timeoutHandler == null : timeoutHandler.equals(replaceMenuParams.timeoutHandler)) &&
        (options == null ? replaceMenuParams.options == null : options.equals(replaceMenuParams.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (greeting == null ? 0: greeting.hashCode());
    result = 31 * result + (invalidKeypress == null ? 0: invalidKeypress.hashCode());
    result = 31 * result + (allowExtensionDial == null ? 0: allowExtensionDial.hashCode());
    result = 31 * result + (keypressWaitTime == null ? 0: keypressWaitTime.hashCode());
    result = 31 * result + (timeoutHandler == null ? 0: timeoutHandler.hashCode());
    result = 31 * result + (options == null ? 0: options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplaceMenuParams {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  greeting: ").append(greeting).append("\n");
    sb.append("  invalidKeypress: ").append(invalidKeypress).append("\n");
    sb.append("  allowExtensionDial: ").append(allowExtensionDial).append("\n");
    sb.append("  keypressWaitTime: ").append(keypressWaitTime).append("\n");
    sb.append("  timeoutHandler: ").append(timeoutHandler).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
