/**
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.ContactSummary;
import io.swagger.client.model.GroupSummary;
import io.swagger.client.model.ScheduleSummary;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


/**
 * Filter Object. Optional. See below for details.
 **/
@ApiModel(description = "Filter Object. Optional. See below for details.")
public class RuleSetFilter  {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("schedule")
  private ScheduleSummary schedule = null;
  @SerializedName("contact")
  private ContactSummary contact = null;
  @SerializedName("group")
  private GroupSummary group = null;

  /**
   * Required.
   **/
  @ApiModelProperty(value = "Required.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Schedule that this filter refers to. Output is a Schedule Summary Object. Input must be a Schedule Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Schedule that this filter refers to. Output is a Schedule Summary Object. Input must be a Schedule Lookup Object. Required.")
  public ScheduleSummary getSchedule() {
    return schedule;
  }
  public void setSchedule(ScheduleSummary schedule) {
    this.schedule = schedule;
  }

  /**
   * Address Book Contact that this filter refers to. Output is a Contact Summary Object. Input must be a Contact Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Address Book Contact that this filter refers to. Output is a Contact Summary Object. Input must be a Contact Lookup Object. Required.")
  public ContactSummary getContact() {
    return contact;
  }
  public void setContact(ContactSummary contact) {
    this.contact = contact;
  }

  /**
   * Address Book Group that this filter refers to. Output is a Contact Group Summary Object. Input must be a Contact Group Lookup Object. Required.
   **/
  @ApiModelProperty(value = "Address Book Group that this filter refers to. Output is a Contact Group Summary Object. Input must be a Contact Group Lookup Object. Required.")
  public GroupSummary getGroup() {
    return group;
  }
  public void setGroup(GroupSummary group) {
    this.group = group;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleSetFilter ruleSetFilter = (RuleSetFilter) o;
    return (type == null ? ruleSetFilter.type == null : type.equals(ruleSetFilter.type)) &&
        (schedule == null ? ruleSetFilter.schedule == null : schedule.equals(ruleSetFilter.schedule)) &&
        (contact == null ? ruleSetFilter.contact == null : contact.equals(ruleSetFilter.contact)) &&
        (group == null ? ruleSetFilter.group == null : group.equals(ruleSetFilter.group));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (type == null ? 0: type.hashCode());
    result = 31 * result + (schedule == null ? 0: schedule.hashCode());
    result = 31 * result + (contact == null ? 0: contact.hashCode());
    result = 31 * result + (group == null ? 0: group.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleSetFilter {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  schedule: ").append(schedule).append("\n");
    sb.append("  contact: ").append(contact).append("\n");
    sb.append("  group: ").append(group).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
