//
// ApplicationSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Application Summary Object is used to briefly represent an application. It can occur in several places throughout this API. Here are the properties: */
public class ApplicationSummary: JSONEncodable {
    /** Application ID. Read-only. */
    public var id: Int32?
    /** Application name */
    public var name: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
