//
// CreateSubaccountParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CreateSubaccountParams: JSONEncodable {
    /** Sub account user name */
    public var username: String?
    /** Sub account password */
    public var password: String?
    /** Contact Object. See below for details. */
    public var contact: ContactSubaccount?
    /** Contact Object for billing purposes. See below for details. */
    public var billingContact: ContactSubaccount?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["username"] = self.username
        nillableDictionary["password"] = self.password
        nillableDictionary["contact"] = self.contact?.encodeToJSON()
        nillableDictionary["billing_contact"] = self.billingContact?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
