//
// CreateMenuParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CreateMenuParams: JSONEncodable {
    public var name: String?
    public var mainMessage: AnyObject?
    public var invalidKeypressMessage: AnyObject?
    public var allowExtensionDial: Bool?
    public var keypressWaitTime: Int32?
    public var timeoutHandler: AnyObject?
    public var options: [AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["main_message"] = self.mainMessage
        nillableDictionary["invalid_keypress_message"] = self.invalidKeypressMessage
        nillableDictionary["allow_extension_dial"] = self.allowExtensionDial
        nillableDictionary["keypress_wait_time"] = self.keypressWaitTime?.encodeToJSON()
        nillableDictionary["timeout_handler"] = self.timeoutHandler
        nillableDictionary["options"] = self.options?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
