//
// DeviceFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Full Device Object includes the properties in the Device Summary Object, along with the following: */
public class DeviceFull: JSONEncodable {
    /** ID */
    public var id: Int32?
    /** User-supplied name, otherwise NULL */
    public var name: String?
    public var sipAuthentication: SipAuthentication?
    /** Array of Line Objects showing which extensions are attached to this device, and their assigned line numbers. See below for details. */
    public var lines: [Line]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["sip_authentication"] = self.sipAuthentication?.encodeToJSON()
        nillableDictionary["lines"] = self.lines?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
