//
// MenuFull.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Full Menu Object contains the same properties as the Menu Summary Object, along with the following: */
public class MenuFull: JSONEncodable {
    /** Integer Menu ID. Read-only. */
    public var id: Int32?
    /** Name. Required. Unique. */
    public var name: String?
    /** Boolean. Determines whether a caller can enter an extension number to bypass the menu. */
    public var allowExtensionDial: Bool?
    /** Boolean. Determines whether a caller can enter an extension number to bypass the menu. */
    public var keypressWaitTime: Int32?
    /** Greeting that is played when a caller enters a menu. Output is a Media Summary Object. Input must be a Media Lookup Object. Must refer to a media recording that has is_hold_music set to FALSE. */
    public var greeting: MediaSummary?
    /** Message that is played when the caller makes a keypress error. Output is a Media Summary Object. Input must be a Media Lookup Object. Must refer to a media recording that has is_hold_music set to FALSE. */
    public var keypressError: MediaSummary?
    /** Route that will be entered when the caller fails to choose a menu option within the allotted time. Output is a Route Summary Object if the route is named, otherwise the Full Route Object will be shown. Input must be a Route Lookup Object pointing to a named route. */
    public var timeoutHandler: RouteSummary?
    public var options: OptionsListMenus?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["allow_extension_dial"] = self.allowExtensionDial
        nillableDictionary["keypress_wait_time"] = self.keypressWaitTime?.encodeToJSON()
        nillableDictionary["greeting"] = self.greeting?.encodeToJSON()
        nillableDictionary["keypress_error"] = self.keypressError?.encodeToJSON()
        nillableDictionary["timeout_handler"] = self.timeoutHandler?.encodeToJSON()
        nillableDictionary["options"] = self.options?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
