//
// Recipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Recipient: JSONEncodable {
    /** Phone number that will receive the SMS message */
    public var number: String?
    /** Indicate the status of your SMS object. May be &#39;sent&#39;, &#39;received&#39;, &#39;queued&#39;, &#39;new&#39; ... */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["number"] = self.number
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
