//
// SipAuthentication.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A SIP Authentication Properties Object. See below for details. Read-only. */
public class SipAuthentication: JSONEncodable {
    /** Hostname */
    public var host: String?
    /** Port number */
    public var port: Int32?
    /** Username. This is the ID of the device. */
    public var username: String?
    /** Password. */
    public var password: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["host"] = self.host
        nillableDictionary["port"] = self.port?.encodeToJSON()
        nillableDictionary["username"] = self.username
        nillableDictionary["password"] = self.password
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
