package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AddressListContacts address list contacts
// swagger:model AddressListContacts
type AddressListContacts struct {

	// City
	City string `json:"city,omitempty"`

	// Country name
	Country string `json:"country,omitempty"`

	// State or province
	State string `json:"state,omitempty"`

	// House number and street name, including apartment, suite, etc.
	Street string `json:"street,omitempty"`

	// Address type, one of: home or business. Default is home.
	Type string `json:"type,omitempty"`

	// Zip code or postal code
	Zip string `json:"zip,omitempty"`
}

// Validate validates this address list contacts
func (m *AddressListContacts) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
