package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContactAccount contact account
// swagger:model ContactAccount
type ContactAccount struct {

	// address
	Address *Address `json:"address,omitempty"`

	// Alternate email address
	AlternateEmail string `json:"alternate_email,omitempty"`

	// Company name
	Company string `json:"company,omitempty"`

	// Fax number
	Fax string `json:"fax,omitempty"`

	// Name. Required.
	Name string `json:"name,omitempty"`

	// Phone number. Required.
	Phone string `json:"phone,omitempty"`

	// Primary email address. Required.
	PrimaryEmail string `json:"primary_email,omitempty"`
}

// Validate validates this contact account
func (m *ContactAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContactAccount) validateAddress(formats strfmt.Registry) error {

	if swag.IsZero(m.Address) { // not required
		return nil
	}

	if m.Address != nil {

		if err := m.Address.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("address")
			}
			return err
		}
	}

	return nil
}
