package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CreateMenuParams create menu params
// swagger:model CreateMenuParams
type CreateMenuParams struct {

	// allow extension dial
	AllowExtensionDial bool `json:"allow_extension_dial,omitempty"`

	// invalid keypress message
	InvalidKeypressMessage interface{} `json:"invalid_keypress_message,omitempty"`

	// keypress wait time
	KeypressWaitTime int64 `json:"keypress_wait_time,omitempty"`

	// main message
	MainMessage interface{} `json:"main_message,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// options
	Options []interface{} `json:"options"`

	// timeout handler
	TimeoutHandler interface{} `json:"timeout_handler,omitempty"`
}

// Validate validates this create menu params
func (m *CreateMenuParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOptions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMenuParams) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Options) { // not required
		return nil
	}

	for i := 0; i < len(m.Options); i++ {

	}

	return nil
}
