package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CreateRouteParams create route params
// swagger:model CreateRouteParams
type CreateRouteParams struct {

	// Extension Reference
	Extension interface{} `json:"extension,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Rule Sets
	Rules []interface{} `json:"rules"`
}

// Validate validates this create route params
func (m *CreateRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRules(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateRouteParams) validateRules(formats strfmt.Registry) error {

	if swag.IsZero(m.Rules) { // not required
		return nil
	}

	for i := 0; i < len(m.Rules); i++ {

	}

	return nil
}
