package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DeleteRoute delete route
// swagger:model DeleteRoute
type DeleteRoute struct {

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this delete route
func (m *DeleteRoute) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
