package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeviceMembership Device Membership Object, or NULL. Read-only. See below for details.
// swagger:model DeviceMembership
type DeviceMembership struct {

	// Device that this extension belongs to. Output is an Device Summary Object.
	Device *DeviceSummary `json:"device,omitempty"`

	// Line number to which this extension is assigned. Integer.
	Line int64 `json:"line,omitempty"`
}

// Validate validates this device membership
func (m *DeviceMembership) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDevice(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceMembership) validateDevice(formats strfmt.Registry) error {

	if swag.IsZero(m.Device) { // not required
		return nil
	}

	if m.Device != nil {

		if err := m.Device.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("device")
			}
			return err
		}
	}

	return nil
}
