package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExpressServiceCodeSummary The Express Service Code Summary Object is used to briefly represent a Express Service Code. It consists of the ID and code:
// swagger:model ExpressServiceCodeSummary
type ExpressServiceCodeSummary struct {

	// An 8-digit number in string format
	ExpressServiceCode string `json:"express_service_code,omitempty"`

	// ID
	ID int64 `json:"id,omitempty"`
}

// Validate validates this express service code summary
func (m *ExpressServiceCodeSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
