package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// MenuSummary The Menu Summary Object is used to briefly represent a menu. It can be seen in several places throughout this API. Here are the properties:
// swagger:model MenuSummary
type MenuSummary struct {

	// Integer Menu ID. Read-only.
	ID int64 `json:"id,omitempty"`

	// Name. Required. Unique.
	Name string `json:"name,omitempty"`
}

// Validate validates this menu summary
func (m *MenuSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
