package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PhoneNumberContact phone number contact
// swagger:model PhoneNumberContact
type PhoneNumberContact struct {

	// Phone number in E.164 format. Read-only.
	Normalized string `json:"normalized,omitempty"`

	// Phone number, as entered. Does not need to be formatted in any particular way. Required.
	Number string `json:"number,omitempty"`

	// Type of phone number, must be one of: home, business, mobile, fax, pager. Default is home.
	Type string `json:"type,omitempty"`
}

// Validate validates this phone number contact
func (m *PhoneNumberContact) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
