package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// SortListPhoneNumbersRegions sort list phone numbers regions
// swagger:model SortListPhoneNumbersRegions
type SortListPhoneNumbersRegions struct {

	// city
	City string `json:"city,omitempty"`

	// country code
	CountryCode string `json:"country_code,omitempty"`

	// country postal code
	CountryPostalCode string `json:"country_postal_code,omitempty"`

	// is toll free
	IsTollFree string `json:"is_toll_free,omitempty"`

	// npa
	Npa string `json:"npa,omitempty"`

	// nxx
	Nxx string `json:"nxx,omitempty"`

	// province postal code
	ProvincePostalCode string `json:"province_postal_code,omitempty"`
}

// Validate validates this sort list phone numbers regions
func (m *SortListPhoneNumbersRegions) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
