//
// SubaccountsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SubaccountsAPI: APIBase {
    /**
     Add a subaccount for the authenticated user or client
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) SMS data 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createAccountSubaccount(accountId accountId: Int32, data: CreateSubaccountParams, completion: ((data: AccountFull?, error: ErrorType?) -> Void)) {
        createAccountSubaccountWithRequestBuilder(accountId: accountId, data: data).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Add a subaccount for the authenticated user or client
     - POST /accounts/{accountId}/subaccounts
     - This service shows the details of an individual Subaccount.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "password" : "aeiou",
  "billing_contact" : "",
  "contact" : {
    "address" : {
      "line_1" : "aeiou",
      "line_2" : "aeiou",
      "country" : "aeiou",
      "province" : "aeiou",
      "city" : "aeiou",
      "postal_code" : "aeiou"
    },
    "phone" : "aeiou",
    "name" : "aeiou",
    "company" : "aeiou",
    "primary_email" : "aeiou",
    "fax" : "aeiou",
    "alternate_email" : "aeiou"
  },
  "name" : "aeiou",
  "master_account" : {
    "name" : "aeiou",
    "id" : ""
  },
  "id" : "",
  "username" : "aeiou"
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter data: (body) SMS data 

     - returns: RequestBuilder<AccountFull> 
     */
    public class func createAccountSubaccountWithRequestBuilder(accountId accountId: Int32, data: CreateSubaccountParams) -> RequestBuilder<AccountFull> {
        var path = "/accounts/{accountId}/subaccounts"
        path = path.stringByReplacingOccurrencesOfString("{accountId}", withString: "\(accountId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = data.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AccountFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get a list of subaccounts for the authenticated user or client
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func listAccountSubaccounts(accountId accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil, completion: ((data: ListAccountsFull?, error: ErrorType?) -> Void)) {
        listAccountSubaccountsWithRequestBuilder(accountId: accountId, filtersId: filtersId, sortId: sortId, limit: limit, offset: offset, fields: fields).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a list of subaccounts for the authenticated user or client
     - GET /accounts/{accountId}/subaccounts
     - This service lists the Subaccount of the authenticated client. In most cases, there will not be any.
     - API Key:
       - type: apiKey Authorization 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "total" : "",
  "offset" : "",
  "limit" : "",
  "filters" : {
    "id" : "aeiou"
  },
  "sort" : {
    "id" : "aeiou"
  },
  "items" : [ {
    "password" : "aeiou",
    "billing_contact" : "",
    "contact" : {
      "address" : {
        "line_1" : "aeiou",
        "line_2" : "aeiou",
        "country" : "aeiou",
        "province" : "aeiou",
        "city" : "aeiou",
        "postal_code" : "aeiou"
      },
      "phone" : "aeiou",
      "name" : "aeiou",
      "company" : "aeiou",
      "primary_email" : "aeiou",
      "fax" : "aeiou",
      "alternate_email" : "aeiou"
    },
    "name" : "aeiou",
    "master_account" : {
      "name" : "aeiou",
      "id" : ""
    },
    "id" : "",
    "username" : "aeiou"
  } ]
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter filtersId: (query) ID filter (optional)
     - parameter sortId: (query) ID sorting (optional)
     - parameter limit: (query) Max results (optional)
     - parameter offset: (query) Results to skip (optional)
     - parameter fields: (query) Field set (optional)

     - returns: RequestBuilder<ListAccountsFull> 
     */
    public class func listAccountSubaccountsWithRequestBuilder(accountId accountId: Int32, filtersId: [String]? = nil, sortId: String? = nil, limit: Int32? = nil, offset: Int32? = nil, fields: String? = nil) -> RequestBuilder<ListAccountsFull> {
        var path = "/accounts/{accountId}/subaccounts"
        path = path.stringByReplacingOccurrencesOfString("{accountId}", withString: "\(accountId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filters[id]": filtersId,
            "sort[id]": sortId,
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
            "fields": fields
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ListAccountsFull>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
