package main

const listAccounts = "list-accounts"
const listMedia = "list-media"
const listMenus = "list-menus"
const listQueues = "list-queues"
const listRoutes = "list-routes"
const listSchedules = "list-schedules"
const listSms = "list-sms"
const listAvailablePhoneNumbers = "list-available-phone-numbers"
const listSubaccounts = "list-subaccounts"
const listApplications = "list-applications"
const listCallLogs = "list-call-logs"
const listDevices = "list-devices"
const listExpressServiceCodes = "list-express-service-codes"
const listExtensions = "list-extensions"
const listContacts = "list-contacts"
const listGroups = "list-groups"
const listPhoneNumbers = "list-phone-numbers"

const getMenu = "get-menu"
const getRecording = "get-recording"
const getQueue = "get-queue"
const getRoute = "get-route"
const getSchedule = "get-schedule"
const getSms = "get-sms"
const getAccount = "get-account"
const getApplication = "get-application"
const getDevice = "get-device"
const getExtension = "get-extension"
const getExpressServiceCode = "get-express-service-code"
const getCallerId = "get-caller-id"
const getContact = "get-contact"
const getGroup = "get-group"
const getPhoneNumber = "get-phone-number"

const createPhoneNumber = "create-phone-number"
const createCall = "create-call"
const createDevice = "create-device"
const createExtension = "create-extension"
const createContact = "create-contact"
const createGroup = "create-group"

const replaceDevice = "replace-device"
const replaceExtension = "replace-extension"
const replaceContact = "replace-contact"
const replaceGroup = "replace-group"
const replacePhoneNumber = "replace-phone-number"

const deleteContact = "delete-contact"
const deleteGroup = "delete-group"
